#23 Option to pass custom headers
observing/thor pull request #25
Opened 2016-01-08 17:08 UTC by reda-alaoui

2017-02-05 19:18 UTC, reda-alaoui commented
Considering this project as dead.

2017-02-05 21:40 UTC, 3rd-Eden commented
Cool.

2017-02-05 22:09 UTC, reda-alaoui commented
No activity on PRs for one year. 
I say that the project is dead, and then magically someone appears and start to process them :)

Sorry if I looked agressive, this wasn't my intent. I was juste cleaning my open PRs. If you are interested in those PRs I can reopen them.

I know that maintaining a project is hard ;)

2017-03-02 11:48 UTC, robertoronderosjr requested changes

2017-03-02 11:48 UTC, robertoronderosjr commented on bin/thor
> +  var keyValue = header.split(':');
Header Val might have ':' therefore the split will be wrong. Try:
var keyValue = header.split(/:/);
var key = keyValue.shift();
var value = keyValue.join(':');

2017-10-24 23:06 UTC, closed without merging